#---
#spring:
#  datasource:
#     driverClassName: "com.mysql.jdbc.Driver"
#     url: "jdbc:mysql://paasword.euprojects.net:8917/xerp"
##     url: "jdbc:mysql://192.168.3.51:3306/xerp"
#     username: "root"
#     password: "!r00t!"
#  jpa:
#    hibernate.ddl-auto: none
#    show_sql: false
